apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Dell\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-web-application
  name: todo-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-web-application
  template:
    metadata:
      labels:
        io.kompose.network/03-todo-web-application-mysql-default: "true"
        io.kompose.service: todo-web-application
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
#              value: todos
              valueFrom:
                configMapKeyRef:
                  key: RDS_DB_NAME
                  name: todo-web-application-config
            - name: RDS_HOSTNAME
#              value: mysql
              valueFrom:
                configMapKeyRef:
                  key: RDS_HOSTNAME
                  name: todo-web-application-config
            - name: RDS_PASSWORD
#              value: dummytodos
              valueFrom:
                configMapKeyRef:
                  key: RDS_PASSWORD
                  name: todo-web-application-config
            - name: RDS_PORT
#              value: "3306"
              valueFrom:
                configMapKeyRef:
                  key: RDS_PORT
                  name: todo-web-application-config
            - name: RDS_USERNAME
#              value: todos-user
              valueFrom:
                configMapKeyRef:
                  key: RDS_USERNAME
                  name: todo-web-application-config
          image: robinroy1999/todo-web-application-mysql:0.0.1-SNAPSHOT
          name: todo-web-application
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
